# Generated by Django 2.2.4 on 2019-10-04 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ipv4', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LockGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('grup', models.ManyToManyField(to='smartlock.Lock', verbose_name='group')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(blank=True, default=None, max_length=256, null=True, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('manager', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDataGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('grup', models.ManyToManyField(to='smartlock.UserData', verbose_name='group')),
            ],
        ),
        migrations.CreateModel(
            name='LockPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smartlock.Lock')),
                ('lockgrup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smartlock.LockGroup', verbose_name='lock group')),
                ('userdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smartlock.UserData')),
                ('userdatagrup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smartlock.UserDataGroup', verbose_name='user group')),
            ],
            options={
                'unique_together': {('userdata', 'userdatagrup', 'lock', 'lockgrup')},
            },
        ),
    ]
