# Generated by Django 2.2.4 on 2019-10-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0002_auto_20191005_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockAttemptLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartlock.Lock')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartlock.UserData')),
            ],
        ),
    ]
