# Generated by Django 2.2.4 on 2019-10-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0004_auto_20191006_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockattemptlog',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smartlock.Lock'),
        ),
        migrations.AlterField(
            model_name='unlockattemptlog',
            name='userdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smartlock.UserData'),
        ),
    ]
