# Generated by Django 2.2.6 on 2019-10-22 20:03

from django.db import migrations, models
import smartlock.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0007_auto_20191017_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='ipv4',
        ),
        migrations.AddField(
            model_name='lock',
            name='ruid',
            field=models.CharField(blank=True, default=smartlock.models.get_ruid, max_length=32, null=True),
        ),
    ]
