# Generated by Django 2.2.6 on 2019-10-22 20:08

from django.db import migrations, models
import smartlock.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0008_auto_20191022_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='ruid',
            field=models.CharField(default=smartlock.models.get_ruid, max_length=32, unique=True),
        ),
    ]
