# Generated by Django 2.2.4 on 2019-10-31 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0010_auto_20191022_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['user__username']},
        ),
        migrations.CreateModel(
            name='LockPermissionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_strt', models.DateField()),
                ('dt_stop', models.DateField()),
                ('tm_strt', models.TimeField()),
                ('tm_stop', models.TimeField()),
                ('mond', models.BooleanField(default=False, verbose_name='monday')),
                ('tues', models.BooleanField(default=False, verbose_name='tuesday')),
                ('wedn', models.BooleanField(default=False, verbose_name='wednesday')),
                ('thur', models.BooleanField(default=False, verbose_name='thursday')),
                ('frid', models.BooleanField(default=False, verbose_name='friday')),
                ('satu', models.BooleanField(default=False, verbose_name='saturday')),
                ('sund', models.BooleanField(default=False, verbose_name='sunday')),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartlock.LockPermission')),
            ],
        ),
    ]
