# Generated by Django 2.2.4 on 2019-11-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0012_auto_20191031_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockpermissionschedule',
            name='dt_stop',
            field=models.DateField(verbose_name='ending date'),
        ),
        migrations.AlterField(
            model_name='lockpermissionschedule',
            name='dt_strt',
            field=models.DateField(verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='lockpermissionschedule',
            name='tm_stop',
            field=models.TimeField(blank=True, null=True, verbose_name='ending time'),
        ),
        migrations.AlterField(
            model_name='lockpermissionschedule',
            name='tm_strt',
            field=models.TimeField(blank=True, null=True, verbose_name='starting time'),
        ),
    ]
