# Generated by Django 2.2.4 on 2019-11-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0014_auto_20191102_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
