# Generated by Django 2.2.4 on 2019-11-03 17:43

from django.db import migrations, models
import django.db.models.deletion
import smartlock.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0016_auto_20191103_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='ruid',
            field=models.CharField(default=smartlock.models.get_ruid, max_length=32, unique=True, verbose_name='RUID'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='tmzn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartlock.TimeZone', verbose_name='timezone'),
        ),
    ]
