# Generated by Django 2.2.4 on 2019-11-03 17:45

from django.db import migrations, models
import smartlock.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0017_auto_20191103_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='ruid',
            field=models.CharField(default=smartlock.models.get_ruid, help_text='Random unique identifier', max_length=32, unique=True, verbose_name='RUID'),
        ),
    ]
