# Generated by Django 2.2.4 on 2019-11-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlock', '0019_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockpermissionschedule',
            name='perm',
        ),
        migrations.AlterModelOptions(
            name='unlockattemptlog',
            options={'ordering': ('-time',)},
        ),
        migrations.DeleteModel(
            name='LockPermission',
        ),
        migrations.DeleteModel(
            name='LockPermissionSchedule',
        ),
    ]
